---
- name: Uninstall unused apps
  dnf:
    name: '{{ item }}'
    state: absent
  loop: '{{ clean_apps }}'
  become: true

- name: Disable pycharm copr
  community.general.copr:
    state: disabled
    name: phracek/PyCharm
  become: true

- name: Disable abrt service
  systemd_service:
    name: abrtd
    state: stopped
    enabled: false
  become: true

- name: Autoremove unneded packages
  dnf:
    autoremove: true
  become: true
