---
- name: Uninstall unused apps
  dnf:
    name: '{{ item }}'
    state: absent
  loop: '{{ clean_apps }}'
  become: true

- name: Disable pycharm copr
  community.general.copr:
    state: disabled
    name: phracek/PyCharm
  become: true
