---
- name: Install flatpak apps
  community.general.flatpak:
    name: '{{ item }}'
    state: present
  loop: '{{ flatpaks }}'
  become: true

- name: Install vscode repo
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true

- name: Install Desktop apps
  dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ desktop_apps }}'
  become: true
