---
- name: Add docker repository
  command: dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
  become: true

- name: Install docker packages
  dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ docker_packages }}}'
  become: true

- name: Enable docker service
  systemd_service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  group:
    name: docker
    state: present
  become: true

- name: Append the group docker to user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
