---
- name: Enable ghostty COPR repository
  community.general.copr:
    state: enabled
    name: pgdev/ghostty
  become: true

- name: Install ghostty
  dnf:
    name: ghostty
    state: present
  become: true
