---
- name: Enable ghostty COPR repository
  become: true
  community.general.copr:
    state: enabled
    name: pgdev/ghostty

- name: Install ghostty
  become: true
  dnf:
    name: ghostty
    state: present

- name: Create fonts dir
  file:
    path: ~/.local/share/fonts
    state: directory
    mode: '0755'

- name: Install Jetbrains Nerd Fonts
  unarchive:
    src: '{{ role_path }}/files/ghostty/jetbrains-nerd-font-mono.zip'
    dest: ~/.local/share/fonts

- name: Create ghostty config dir
  file:
    path: ~/.config/ghostty
    state: directory
    mode: '0755'

- name: Config ghostty
  copy:
    src: '{{ role_path }}/files/ghostty/config'
    dest: '~/.config/ghostty'
    mode: '644'
