---
- name: Config git username
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: Config git e-mail
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Config git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: "nvim"

- name: Config git default branch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: "main"

- name: Config git credential store
  community.general.git_config:
    name: credential.helper
    scope: global
    value: "store"
