---
- name: Clone WhiteSur repo
  git:
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    dest: /tmp/whitesur
    version: v2025-02-10

- name: Install WhiteSur icon theme
  become: true
  command: /tmp/whitesur/install.sh -a -b -d /usr/share/icons

- name: Set icon theme in GDM
  become: true
  copy:
    src: '{{ role_path }}/files/99-custom-settings'
    dest: '/etc/dconf/db/gdm.d'
    owner: root
    group: root
    mode: '644'

- name: Set icon theme in GDM
  become: true
  copy:
    src: '{{ role_path }}/files/99-custom-settings'
    dest: '/etc/dconf/db/local.d/'
    owner: root
    group: root
    mode: '644'

- name: Update dconf
  become: true
  command: dconf update
