---
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: true

- name: Install add-ons
  dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ addons }}'
  become: true

- name: Create config dir
  file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Install ghostty terminal
  include_tasks: ghostty.yml

- name: Install docker
  include_tasks: docker.yml

- name: Install CLI tools
  include_tasks: cli.yml

- name: Config git
  include_tasks: git.yml

- name: Config neovim
  include_tasks: nvim.yml

- name: Config virtualization
  include_tasks: vms.yml

- name: Install desktop apps
  include_tasks: desktop.yml

- name: Clean unused apps & configs
  include_tasks: clean.yml
