---
- name: Upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest

- name: Install add-ons
  become: true
  dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ addons }}'

- name: Create config dir
  file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Install ghostty terminal
  include_tasks: ghostty.yml

- name: Install docker
  include_tasks: docker.yml

- name: Install CLI tools
  include_tasks: cli.yml

- name: Config git
  include_tasks: git.yml

- name: Config neovim
  include_tasks: nvim.yml

- name: Config virtualization
  include_tasks: vms.yml

- name: Install desktop apps
  include_tasks: desktop.yml

- name: Clean unused apps & configs
  include_tasks: clean.yml

- name: Config gnome
  include_tasks: gnome.yml

- name: Enable remote access
  include_tasks: remote-access.yml
