---
- name: Check if neovim configuration is installed
  stat:
    path: '~/.config/nvim' 
  register: nvim_config

- name: Clone the neovim configuration repository
  git:
    repo: 'https://github.com/ph777z/configs.nvim.git'
    dest: '~/.config/nvim'
  when: not (nvim_config.stat.exists and nvim_config.stat.isdir)

- name: Install neovim npm package
  become: true
  community.general.npm:
    name: neovim
    global: true
