---
- name: Enable SSH service
  become: true
  systemd_service:
    name: sshd
    state: started
    enabled: true
  when: activate_ssh

- name: Install tailscale
  become: true
  dnf:
    name: tailscale
    state: present

- name: Enable tailscale service
  become: true
  systemd_service:
    name: tailscaled
    state: started
    enabled: true
